<h1 style = "color : teal"> One Hot Encoding </h1>
One-Hot Encoding (OHE) creates a binary column for every distinct category present in the nominal feature

In [8]:
import numpy as np 
import pandas as pd

In [9]:
df = pd.read_csv('cars.csv')

In [10]:
df.sample(6)

        brand  km_driven    fuel         owner  selling_price
7087   Maruti      25000  Petrol   First Owner         260000
6044      BMW      50000  Diesel   First Owner        1800000
3782   Maruti      20000  Petrol   First Owner         500000
2892   Nissan      90000  Diesel  Second Owner         580000
4552  Hyundai      20000  Petrol   First Owner         570000
523      Tata      42000  Petrol   First Owner         425000

In [11]:
# checking the counts of each brand type 
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

<h1 style = "color : teal">One Hot Encoding using Pandas</h1>

In [12]:
# get_dummies function helps to do one hot encoding using pandas 
pd.get_dummies(df, columns = ['owner', 'fuel'], dtype = int)

# df is the dataframe and columns attribute holds the list of columns to be encoded else all columns are encoded
# by default the datatype returned is boolean so dtype is used to transoform

,brand,km_driven,selling_price,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,Maruti,145500,450000,1,0,0,0,0,0,1,0,0
1,Skoda,120000,370000,0,0,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,1,0,0
4,Maruti,120000,130000,1,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,1,0,0,0,0,0,0,0,1
8124,Hyundai,119000,135000,0,1,0,0,0,0,1,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,1,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,1,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,1,0,0

<h1 style = "color : teal">Drop the first column </h1>

In [13]:
# dropping the first column because,
# This creates perfect multicollinearity—a condition where one input feature can be predicted linearly from the remaining input features

pd.get_dummies(df, columns = ['owner', 'fuel'], drop_first = True, dtype = int)

,brand,km_driven,selling_price,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_Diesel,fuel_LPG,fuel_Petrol
0,Maruti,145500,450000,0,0,0,0,1,0,0
1,Skoda,120000,370000,0,1,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,1
3,Hyundai,127000,225000,0,0,0,0,1,0,0
4,Maruti,120000,130000,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,0,0,0,1
8124,Hyundai,119000,135000,1,0,0,0,1,0,0
8125,Maruti,120000,382000,0,0,0,0,1,0,0
8126,Tata,25000,290000,0,0,0,0,1,0,0
8127,Tata,25000,290000,0,0,0,0,1,0,0

<h1 style = "color : teal">Using Scikit Learn

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 0:4], df.iloc[:, -1], test_size = 0.2, random_state = 2)

In [15]:
X_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [16]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output = False, dtype = np.int32, drop = 'first')

# the OneHotEncoder class returns a sparse matrix so we pass sparse_output = False to get an numpy array
# the np arrya is float so dtype helps to get required datatype
# drop attribute helps to drop the first column from all the features that are using this class

In [17]:
ohe.fit_transform(X_train[['fuel', 'owner']])

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], shape=(6502, 7), dtype=int32)

In [18]:
ohe.transform(X_test[['fuel', 'owner']])

array([[0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], shape=(1626, 7), dtype=int32)

In [19]:
X_train_new = ohe.fit_transform(X_train[['fuel', 'owner']])
X_test_new = ohe.transform(X_test[['fuel', 'owner']])

In [20]:
# adding the encoded columns with other columns
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], shape=(6502, 9), dtype=object)

<h1 style = "color : deeppink">One Hot Encoding For vast Categories

In [21]:
counts = df['brand'].value_counts()
df['brand'].nunique()
threshold = 100

In [22]:
repl = counts[counts <= threshold].index

In [23]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon'), dtype = int).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
7549,0,0,0,0,0,0,1,0,0,0,0,0,0
6922,0,0,0,0,0,0,1,0,0,0,0,0,0
1353,0,0,0,0,0,0,1,0,0,0,0,0,0
2596,0,0,0,0,0,0,0,0,0,0,0,0,1
1847,0,0,0,0,0,0,1,0,0,0,0,0,0